trigger:
  branches:
    include:
      - main
      - master

pr:
  branches:
    include:
      - main
      - master

jobs:
- job: test
  timeoutInMinutes: 60
  pool:
    name: 'Default'
  steps:
  - checkout: self

  - task: UseNode@1
    inputs:
      version: '18.x'

  - script: npm ci
    displayName: 'Install dependencies'

  - script: npx playwright install --with-deps
    displayName: 'Install Playwright Browsers'

  - script: npx playwright test --reporter=line,allure-playwright --output=allure-results
    displayName: 'Run Playwright tests'

  - script: npx allure generate allure-results --clean -o allure-report
    displayName: 'Generate Allure report'

  - task: PublishBuildArtifacts@1
    inputs:
      PathtoPublish: 'allure-report'
      ArtifactName: 'allure-report'
      retentionPolicy: '30'
